def studentData(stno,studept,stuname,stage,stmarks):
    print("{}\t{}\t{}\t{}\t{}\t".format(stno,studept,stuname,stage,stmarks))
print("_"*50)    
print("student Details")
print("_"*50)
print("stno\tstudept\tstuname\tstage\tstmarks")
print("_"*50)
studentData(10,"ECE","Madhu",26,95)
print("_"*50)
def studentData(stno,studept,stuname,stage,stmarks):
    print("{}\t{}\t{}\t{}\t{}\t".format(stno,studept,stuname,stage,stmarks))
print("_"*50)    
print("student Details")
print("_"*50)
print("stno\tstudept\tstuname\tstage\tstmarks")
print("_"*50)
studentData(10,"ECE","NAVADEEP",26,95)
print("_"*50)
def studentData(stno,studept,stuname,stage,stmarks):
    print("{}\t{}\t{}\t{}\t{}\t".format(stno,studept,stuname,stage,stmarks))
print("_"*50)    
print("student Details")
print("_"*50)
print("stno\tstudept\tstuname\tstage\tstmarks")
print("_"*50)
studentData(10,"ECE","PREMKUMAR",26,95)
print("_"*50)
def studentData(stno,studept,stuname,stage,stmarks):
    print("{}\t{}\t{}\t{}\t{}\t".format(stno,studept,stuname,stage,stmarks))
print("_"*50)    
print("student Details")
print("_"*50)
print("stno\tstudept\tstuname\tstage\tstmarks")
print("_"*50)
studentData(10,"ECE","PRAVEEN",26,95)
print("_"*50)
def studentData(stno,studept,stuname,stage,stmarks):
    print("{}\t{}\t{}\t{}\t{}\t".format(stno,studept,stuname,stage,stmarks))
print("_"*50)    
print("student Details")
print("_"*50)
print("stno\tstudept\tstuname\tstage\tstmarks")
print("_"*50)
studentData(10,"ECE","ADITYA",26,95)
print("_"*50)